FROM golang:1.21.7-alpine

# Install gcc and musl-dev
RUN apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go/go.mod ./go/
COPY go/go.sum ./go/
# COPY ../db /db

RUN chown -R trainee:mercari /db

RUN go mod tidy

COPY db/ ./db/
COPY go/ ./go/

WORKDIR /app/go

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN go build -o ./mercari-build-training ./app/*.go
RUN chown -R trainee:mercari /app

USER trainee

EXPOSE 9000

CMD ["go", "run", "main.go"]