FROM node:20-alpine
WORKDIR /app

COPY package*.json ./

RUN npm install

RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari ./ 
USER trainee
COPY . .

EXPOSE 3000

CMD ["npm", "start"]
# CMD ["node", "-v"]
