- name: Build and push Docker image
  uses: docker/build-push-action@v2
  with:
    context: .
    file: Dockerfile
    push: true
    tags: ghcr.io/${{ Raychel-310 }}/mercari-build-training:${{ step6 }}
